### ISSUE TITLE
poetry can't be recognized

### ISSUE THREAD

**Issue by koelvijver** [kburel/SNN_HFO_iEEG#110]
After trying to install poetry via the instructions the same problem keeps recurring. 
I tried adding ...\Python38\site-packages\poetry to the path of systemvariables, but with no result.
Trying to run the code without installation was not succesfull either.

What step do I take in order to run the code? thanks in advance!

![image](https://user-images.githubusercontent.com/95621181/145089267-81ada757-c771-4c2e-b475-31796ad719ab.png)

With kind regards, Koen

EDIT: %USERPROFILE%\.poetry\bin needed to be added to the path instead of the path above.

**Comment by quincyrondei** [comment]
Have you tried the method that poetry themselves suggest? I also couldn't do it through the method here that is advised here. I assume poetry updated in the mean time. See https://python-poetry.org/docs/:

curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -

**Comment by koelvijver** [comment]
This indeed worked. Adding %USERPROFILE%.poetry\bin to the systemvariables path was nescessary as well (as stated in their installation manual)  Thanks 😊 Van: quincyrondeiVerzonden: woensdag 8 december 2021 08:25Aan: kburel/snn-hfo-detectionCC: koelvijver; AuthorOnderwerp: Re: [kburel/snn-hfo-detection] poetry can't be recognized (Issue #110) Have you tried the method that poetry themselves suggest? I also couldn't do it through the method here that is advised here. I assume poetry updated in the mean time. See https://python-poetry.org/docs/:curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by quincyrondei** [comment]
Dear Koen (Hoi Koen, gezien je naam) I'm happy to have been of help. I deleted my initial reaction because I realised you were using Windows and not Mac as I do.
